In [2]:
import pandas as pd
a1 = pd.Series(("CA-2016-152156",
"CA-2016-152156",
"CA-2016-138688",
"US-2015-108966",
"US-2015-108966",
"CA-2014-115812",
"CA-2014-115812",
"CA-2014-115812",
"CA-2014-115812",
"CA-2014-115812",
"CA-2014-115812",
"CA-2014-115812",
"CA-2017-114412",
"CA-2016-161389",
"US-2015-118983",
"US-2015-118983",
"CA-2014-105893",
"CA-2014-167164",
"CA-2014-143336",
"CA-2014-143336",
"CA-2014-143336",
"CA-2016-137330",
"CA-2016-137330",
"US-2017-156909",
"CA-2015-106320",
"CA-2016-121755",
"CA-2016-121755",
"US-2015-150630",
"US-2015-150630",
"US-2015-150630",
"US-2015-150630",
"US-2015-150630",
"US-2015-150630",
"US-2015-150630",
"CA-2017-107727",
"CA-2016-117590",
"CA-2016-117590",
"CA-2015-117415",
"CA-2015-117415",
"CA-2015-117415",
"CA-2015-117415",
"CA-2017-120999",
"CA-2016-101343",
"CA-2017-139619",
"CA-2016-118255",
"CA-2016-118255",
"CA-2014-146703",
"CA-2016-169194",
"CA-2016-169194",
"CA-2015-115742",
"CA-2015-115742",
"CA-2015-115742",
"CA-2015-115742",
"CA-2016-105816",
"CA-2016-105816",
"CA-2016-111682",
"CA-2016-111682",
"CA-2016-111682",
"CA-2016-111682",
"CA-2016-111682",
"CA-2016-111682",
"CA-2016-111682",
"CA-2015-135545",
"CA-2015-135545",
"CA-2015-135545",
"CA-2015-135545",
"US-2015-164175",
"CA-2014-106376",
"CA-2014-106376",
"CA-2016-119823",
"CA-2016-106075",
"CA-2017-114440",
"US-2015-134026",
"US-2015-134026",
"US-2015-134026",
"US-2017-118038",
"US-2017-118038",
"US-2017-118038",
"US-2014-147606",
"CA-2016-127208",
"CA-2016-127208",
"CA-2014-139451",
"CA-2014-139451",
"CA-2015-149734",
"US-2017-119662",
"CA-2017-140088",
"CA-2017-155558",
"CA-2017-155558",
"CA-2016-159695",
"CA-2016-109806",
"CA-2016-109806",
"CA-2016-109806",
"CA-2015-149587",
"CA-2015-149587",
"CA-2015-149587",
"US-2017-109484",
"CA-2017-161018",
"CA-2017-157833",
"CA-2016-149223",
"CA-2016-158568"))
a3 = pd.Series(('EB-13930',
'EB-13930',
'MO-17950',
'JO-15550',
'JO-15550',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'GB-14530',
'PW-19030',
'RB-19570',
'RB-19570',
'JS-15940',
'SB-20170',
'HL-15040',
'HL-15040',
'HL-15040',
'DK-13225',
'DK-13225',
'CV-12805',
'NS-18640',
'AF-10885',
'AF-10885',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'BC-11125',
'JS-15595',
'JS-15595',
'CS-12355',
'CS-12355',
'CS-12355',
'CS-12355',
'JK-15205',
'SC-20695',
'JD-15895',
'CC-12475',
'CC-12475',
'PM-19135',
'CR-12580',
'CR-12580',
'TB-21400',
'TB-21400',
'TB-21400',
'TB-21400',
'SR-20740',
'SR-20740',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'EB-13870',
'EB-13870',
'EB-13870',
'EB-13870',
'QJ-19255',
'RC-19825',
'RC-19825',
'RE-19450',
'RB-19645',
'DL-13315',
'JL-15130',
'JL-15130',
'JL-15130',
'BO-11425',
'BO-11425',
'BO-11425',
'CL-12565',
'LM-17065',
'LM-17065',
'JM-15535',
'JM-15535',
'RP-19855',
'AG-10525',
'GH-14410',
'TS-21205',
'TS-21205',
'AF-10885',
'FM-14380',
'FM-14380',
'FM-14380',
'NS-18640',
'NS-18640',
'NS-18640',
'JR-15700',
'AJ-10945',
'BM-11575',
'CV-12805',
'DK-12835'
))
a4 = pd.Series(('Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Гишүүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Гишүүн',
'Гишүүн',
'Гишүүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Гишүүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Гишүүн',
'Хувь хүн',
'Байгууллага',
'Гишүүн'
))
a5 = pd.Series(('Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Сүхбаатар',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Сүхбаатар',
'Чингэлтэй',
'Баянзүрх',
'Баянзүрх',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Чингэлтэй',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Сүхбаатар',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй'
))

a6 = pd.Series(('Чихэр, печенье',
'OO ийн цаас, сальфетка',
'Чихэр, печенье',
'Хиам бууз',
'Ундаа ус',
'Жимс ногоо',
'Гурил будаа',
'Бичиг хэрэг',
'OO ийн цаас, сальфетка',
'Ундаа ус',
'OO ийн цаас, сальфетка',
'Ундаа ус',
'Архи пиво',
'Талх, нарийн боов',
'Ундаа ус',
'Ундаа ус',
'Саван бок',
'Зайрмаг',
'Бэлэн гоймон',
'Чихэр, печенье',
'Ундаа ус',
'OO ийн цаас, сальфетка',
'Хиам бууз',
'Зайрмаг',
'Гэр ахуй',
'Набор, шоколад, бохь',
'Чихэр, печенье',
'Гэр ахуй',
'Гурил будаа',
'Бэлэн гоймон',
'Ундаа ус',
'Жимс ногоо',
'Ундаа ус',
'Набор, шоколад, бохь',
'УНДАА УС',
'Самар чипс',
'Зайрмаг',
'ОО сойз',
'Гурил будаа',
'Архи пиво',
'Амтлагч',
'Гурил будаа',
'Чихэр, печенье',
'Ундаа ус',
'Ундаа ус',
'Саван бок',
'Бэлэн гоймон',
'Гурил будаа',
'Амтлагч',
'OO ийн цаас, сальфетка',
'Гурил будаа',
'Ундаа ус',
'Ундаа ус',
'Жимс ногоо',
'Амтлагч',
'OO ийн цаас, сальфетка',
'Самар чипс',
'Хиам бууз',
'OO ийн цаас, сальфетка',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Чихэр, печенье',
'Гоо сайхан',
'Саван бок',
'Чихэр, печенье',
'Гоо сайхан',
'Чихэр, печенье',
'Архи пиво',
'Архи пиво',
'Ундаа ус',
'Амтлагч',
'Гурил будаа',
'Самар чипс',
'Ундаа ус',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Гэр ахуй',
'Амтлагч',
'Жимс ногоо',
'Жимс ногоо',
'Чихэр, печенье',
'Самар чипс',
'Гэр ахуй',
'Ундаа ус',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Ундаа ус',
'Чихэр, печенье',
'Ундаа ус',
'Архи пиво',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Чихэр, печенье',
'Гэр ахуй',
'Бэлэн гоймон',
'Чихэр, печенье',
'Архи пиво',
'Зайрмаг',
'Компот варенье, хүүхдийн тэжээл',
'Самар чипс',
'Набор, шоколад, бохь',
'Архи пиво',
'Бэлэн гоймон'
))
a7 = pd.Series(('Shokolinsen 250 гр',
'Хэрэглээ 00ийн цаас',
'Алимтай жигнэмэг 230 гр',
'Золотой янта 500 гр',
'Punch 450 мл',
'Помидор том',
'Слава хивэг 400 гр',
'Үзгэн бал арилгадаг',
'Lady 20 ш',
'370 Жүүс 370 мл',
'Саль ариун 30 ш',
'Pysio 300 мл',
'A vodka 0.5',
'Өгөөж танзуур',
'Vita жимстэй ус 510 мл',
'Алое шилтэй 180 мл',
'Power 400 g',
'Пломбир на сливках 80 гр савтай',
'Удон гоймон ууттай',
'M&M 45 гр',
'Витафит ус 500 мл',
'Памперс №4',
'Solpro майонез 3 л 67 %',
'Магнат 80 гр',
'Хувцасны өлгүүр 5 ш алаг',
'Шингэн чихэр',
'Akuku резин 90 гр',
'Сахлын татуурга Gilette',
'Русский сахар 250 гр',
'Бэлэн гоймон төмстэй',
'Хүслийн ундаа 500 мл',
'Помидор том',
'Arizona лаазтай 680 мл',
'Jacobs кофе',
'Өглөө сүү',
'Амт чипс 55 гр',
'Эгоист 65 гр',
'Colgate total 100 гр',
'Слава гурвалжин будаа 650 гр',
'Хараа 0.75 цэвэр',
'Вигора 200 гр',
'Давс 1 кг',
'Mini cracker 350 гр',
'Arizona лаазтай 680 мл',
'Тоник лаазтай 330 мл',
'Tide 450 гр авто',
'Paldo king noodle 110 гр',
'Цесна 25 кг',
'Appetita плова',
'Саль ариун 100 ш',
'Слава каш 1 кг',
'Моя семъя 1 л',
'Зуун наст 1.25 мл',
'Мандарин',
'Appetita будаатай хуурга',
'Цэвэрхэн 00ийн цаас',
'Siesta үзэм 200 гр',
'Махеевь салатны 400 мл',
'Selpak 2 хайрцаг',
'Oleina тос 1 л',
'Чихэр кг Кокос 400 гр',
'Nivea тос 50 мл',
'Омо 100 гр',
'Өгөөж вафли',
'Head & Shoulders 400 мл',
'Жимстэй чокопай 6 ш',
'Соёолж 2.5 л',
'Тэргүүн 0.5',
'Витсамо ус 500 мл',
'Дашида 50 гр',
'Заантай будаа 5 кг',
'Lays чипс 80 гр',
'Алое шилтэй 180 мл',
'Хавиргатай рагу 454 гр',
'Хутга 1 ш',
'Appetita будаатай хуурга',
'Нандин чавга 250 гр',
'Чинжүү',
'Чихэр кг Конфет Кино 400 гр',
'Cocoro 100 гр',
'3н өнгийн алчуур',
'Оргилуун ус жимстэй 500 мл',
'Видан зөгийн бал',
'Сор жүүс 200 мл',
'Гурвалжин шоко 22 гр',
'Гоё тетра 1 л',
'Хараа 0.75 цэвэр',
'Шпрот урт татдаг 190 гр',
'Bagro хүрэн манжингийн салат 500 мл',
'Цагаан самар 50 гр',
'Махны мод дугуй',
'Биг ланч 110 гр савтай',
'Custard 6 ш',
'Алтантүрүү 0.5',
'Фифти фифти 180 гр',
'Hainich нухаш',
'Lays чипс 80 гр',
'Монстров 23 гр',
'Арвай 0.100',
'Тэйсти гоймон 110 гр'
))
a8 =pd.Series ((3300,
500,
3100,
2800,
1150,
4000,
750,
2500,
2200,
850,
2200,
1700,
9000,
3000,
1050,
1100,
1600,
1200,
1200,
1000,
450,
1000,
7700,
2500,
2500,
2100,
1500,
550,
1100,
1200,
1050,
4000,
2500,
240,
2600,
1300,
900,
4400,
2100,
11500,
1500,
200,
3500,
2500,
1250,
4100,
2200,
45000,
450,
1400,
2000,
3200,
1900,
4500,
350,
400,
2700,
1700,
4800,
4200,
5500,
3300,
900,
1950,
12000,
2300,
5700,
7600,
500,
800,
13200,
2300,
1100,
3400,
3000,
350,
2000,
4000,
3000,
2300,
1100,
1050,
3300,
500,
600,
1600,
11500,
3500,
2200,
500 ,
13000, 
2300, 
2300,
12500,
2750,
3300,
2300,
500,
2000,
1800
))
a9 =pd.Series ((2,
3,
2,
5,
2,
7,
4,
6,
3,
5,
9,
4,
3,
3,
5,
3,
6,
2,
2,
3,
4,
7,
7,
2,
3,
2,
3,
7,
2,
3,
2,
6,
6,
2,
3,
7,
5,
9,
3,
3,
4,
4,
2,
2,
2,
2,
4,
3,
2,
6,
6,
2,
1,
7,
5,
6,
5,
5,
2,
2,
4,
1,
2,
6,
3,
4,
5,
8,
4,
2,
1,
3,
8,
2,
1,
3,
3,
3,
5,
1,
3,
5,
1,
7,
3,
2,
1,
2,
7,
3,
2,
1,
2,
3,
2,
1,
7,
3,
6,
7))
a10 = pd.Series((
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0.03,
0.03,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0.03,
0,
0,
0.03,
0.03,
0.03,
0.03,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0.03,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0.03,
0,
0,
0,
0.03,
0,
0,
0,
0,
0,
0,
0.03,
0.03,
0,
0,
0.03
))
a11 = pd.Series((6600,
1500,
6200,
14000,
2300,
28000,
3000,
15000,
6600,
4250,
19800,
6800,
27000,
9000,
5092.5,
3201,
9600,
2400,
2400,
3000,
1800,
7000,
53900,
5000,
7500,
4200,
4500,
3850,
2200,
3600,
2100,
24000,
15000,
480,
7566,
9100,
4500,
38412,
6111,
33465,
5820,
800,
7000,
5000,
2500,
8200,
8800,
135000,
900,
8400,
12000,
6400,
1900,
31500,
1750,
2400,
13500,
8500,
9600,
8400,
22000,
3300,
1800,
11700,
36000,
9200,
27645,
60800,
2000,
1600,
13200,
6900,
8800,
6800,
3000,
1050,
6000,
12000,
15000,
2300,
3300,
5250,
3300,
3500,
1746,
3200,
11500,
7000,
14938,
1500,
26000,
2300,
4600,
37500,
5500,
3201,
15617,
1500,
12000,
12222
))
a2 = pd.Series(('08.11.16',
'08.11.16',
'12.06.16',
'11.10.15',
'11.10.15',
'09.06.14',
'09.06.14',
'09.06.14',
'09.06.14',
'09.06.14',
'09.06.14',
'09.06.14',
'15.04.17',
'05.12.16',
'22.11.15',
'22.11.15',
'11.11.14',
'13.05.14',
'27.08.14',
'27.08.14',
'27.08.14',
'09.12.16',
'09.12.16',
'16.07.17',
'25.09.15',
'16.01.16',
'16.01.16',
'17.09.15',
'17.09.15',
'17.09.15',
'17.09.15',
'17.09.15',
'17.09.15',
'17.09.15',
'19.10.17',
'08.12.16',
'08.12.16',
'27.12.15',
'27.12.15',
'27.12.15',
'27.12.15',
'10.09.17',
'17.07.16',
'19.09.17',
'11.03.16',
'11.03.16',
'20.10.14',
'20.06.16',
'20.06.16',
'18.04.15',
'18.04.15',
'18.04.15',
'18.04.15',
'11.12.16',
'11.12.16',
'17.06.16',
'17.06.16',
'17.06.16',
'17.06.16',
'17.06.16',
'17.06.16',
'17.06.16',
'24.11.15',
'24.11.15',
'24.11.15',
'24.11.15',
'30.04.15',
'05.12.14',
'05.12.14',
'04.06.16',
'18.09.16',
'14.09.17',
'26.04.15',
'26.04.15',
'26.04.15',
'09.12.17',
'09.12.17',
'09.12.17',
'26.11.14',
'12.06.16',
'12.06.16',
'12.10.14',
'12.10.14',
'03.09.15',
'13.11.17',
'28.05.17',
'26.10.17',
'26.10.17',
'05.04.16',
'17.09.16',
'17.09.16',
'17.09.16',
'31.01.15',
'31.01.15',
'31.01.15',
'06.11.17',
'09.11.17',
'17.06.17',
'06.09.16',
'29.08.16'
))
a2
states = pd.DataFrame({'Order ID': a1,
                       'Order Date':a2,
                       'Customer ID': a3,
                       'Segment' : a4,
                       'Region' : a5,
                       'Category' : a6,
                       'Product Name' : a7,
                       'Price' : a8, 
                       'Quantity' : a9,
                       'Discount' : a10,
                       'Sales' : a11

})
states

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
0,CA-2016-152156,08.11.16,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,0.00,6600.0
1,CA-2016-152156,08.11.16,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,0.00,1500.0
2,CA-2016-138688,12.06.16,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,0.00,6200.0
3,US-2015-108966,11.10.15,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,0.00,14000.0
4,US-2015-108966,11.10.15,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,0.00,2300.0
...,...,...,...,...,...,...,...,...,...,...,...
95,US-2017-109484,06.11.17,JR-15700,Гишүүн,Хан-Уул,"Компот варенье, хүүхдийн тэжээл",Hainich нухаш,3300,1,0.03,3201.0
96,CA-2017-161018,09.11.17,AJ-10945,Гишүүн,Сүхбаатар,Самар чипс,Lays чипс 80 гр,2300,7,0.03,15617.0
97,CA-2017-157833,17.06.17,BM-11575,Хувь хүн,Хан-Уул,"Набор, шоколад, бохь",Монстров 23 гр,500,3,0.00,1500.0
98,CA-2016-149223,06.09.16,CV-12805,Байгууллага,Чингэлтэй,Архи пиво,Арвай 0.100,2000,6,0.00,12000.0
99,CA-2016-158568,29.08.16,DK-12835,Гишүүн,Чингэлтэй,Бэлэн гоймон,Тэйсти гоймон 110 гр,1800,7,0.03,12222.0

In [27]:
#1 Эхний 10 мөрийг сонгож авна уу
states.iloc[:10, :11]

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
0,CA-2016-152156,08.11.16,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,0.0,6600.0
1,CA-2016-152156,08.11.16,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,0.0,1500.0
2,CA-2016-138688,12.06.16,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,0.0,6200.0
3,US-2015-108966,11.10.15,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,0.0,14000.0
4,US-2015-108966,11.10.15,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,0.0,2300.0
5,CA-2014-115812,09.06.14,RH-19600,Хувь хүн,Хан-Уул,Жимс ногоо,Помидор том,4000,7,0.0,28000.0
6,CA-2014-115812,09.06.14,RH-19600,Хувь хүн,Хан-Уул,Гурил будаа,Слава хивэг 400 гр,750,4,0.0,3000.0
7,CA-2014-115812,09.06.14,RH-19600,Хувь хүн,Хан-Уул,Бичиг хэрэг,Үзгэн бал арилгадаг,2500,6,0.0,15000.0
8,CA-2014-115812,09.06.14,RH-19600,Хувь хүн,Хан-Уул,"OO ийн цаас, сальфетка",Lady 20 ш,2200,3,0.0,6600.0
9,CA-2014-115812,09.06.14,RH-19600,Хувь хүн,Хан-Уул,Ундаа ус,370 Жүүс 370 мл,850,5,0.0,4250.0

In [28]:
#2 78-88 дугаар мөрөнд байгаа мэдээллээс Product Name, Sales багануудыг харуулна уу
b = states.iloc[77:88]
d=b['Sales']
v=b['Product Name']
d, v

(77    12000.0
 78    15000.0
 79     2300.0
 80     3300.0
 81     5250.0
 82     3300.0
 83     3500.0
 84     1746.0
 85     3200.0
 86    11500.0
 87     7000.0
 Name: Sales, dtype: float64,
 77                         Чинжүү
 78    Чихэр кг Конфет Кино 400 гр
 79                  Cocoro 100 гр
 80               3н өнгийн алчуур
 81     Оргилуун ус жимстэй 500 мл
 82               Видан зөгийн бал
 83                Сор жүүс 200 мл
 84           Гурвалжин шоко 22 гр
 85                  Гоё тетра 1 л
 86               Хараа 0.75 цэвэр
 87        Шпрот урт татдаг 190 гр
 Name: Product Name, dtype: object)

In [29]:
#3 Quantity болон Sales баганыг сонгож авна уу.

d=states['Sales']
v=states['Quantity']
v,  d

(0     2
 1     3
 2     2
 3     5
 4     2
      ..
 95    1
 96    7
 97    3
 98    6
 99    7
 Name: Quantity, Length: 100, dtype: int64,
 0      6600.0
 1      1500.0
 2      6200.0
 3     14000.0
 4      2300.0
        ...
 95     3201.0
 96    15617.0
 97     1500.0
 98    12000.0
 99    12222.0
 Name: Sales, Length: 100, dtype: float64)

In [30]:
#4 Quantity болон Sales баганын нийлбэрүүдийг харуулна уу.
d=states['Sales']
v=states['Quantity']
sales_sum=d.sum( axis = 0)
quantity_sum=v.sum(axis = 0)
quantity_sum, sales_sum

(374, 1115166.5)

In [31]:
#5 . Product Name баганыг сонгож авна уу
q=states['Product Name']
q

0          Shokolinsen 250 гр
1         Хэрэглээ 00ийн цаас
2     Алимтай жигнэмэг 230 гр
3         Золотой янта 500 гр
4                Punch 450 мл
               ...
95              Hainich нухаш
96            Lays чипс 80 гр
97             Монстров 23 гр
98                Арвай 0.100
99       Тэйсти гоймон 110 гр
Name: Product Name, Length: 100, dtype: object

In [32]:
#6 Product Name баганын давхардаагүй утгуудыг харуулна уу.

w=q.unique()
w

array(['Shokolinsen 250 гр', 'Хэрэглээ 00ийн цаас',
       'Алимтай жигнэмэг 230 гр', 'Золотой янта 500 гр', 'Punch 450 мл',
       'Помидор том', 'Слава хивэг 400 гр', 'Үзгэн бал арилгадаг',
       'Lady 20 ш', '370 Жүүс 370 мл', 'Саль ариун 30 ш', 'Pysio 300 мл',
       'A vodka 0.5', 'Өгөөж танзуур', 'Vita жимстэй ус 510 мл',
       'Алое шилтэй 180 мл', 'Power 400 g',
       'Пломбир на сливках 80 гр савтай', 'Удон гоймон ууттай',
       'M&M 45 гр', 'Витафит ус 500 мл', 'Памперс №4',
       'Solpro майонез 3 л 67 %', 'Магнат 80 гр',
       'Хувцасны өлгүүр 5 ш алаг', 'Шингэн чихэр', 'Akuku резин 90 гр',
       'Сахлын татуурга Gilette', 'Русский сахар 250 гр',
       'Бэлэн гоймон төмстэй', 'Хүслийн ундаа 500 мл',
       'Arizona лаазтай 680 мл', 'Jacobs кофе', 'Өглөө сүү',
       'Амт чипс 55 гр', 'Эгоист 65 гр', 'Colgate total 100 гр',
       'Слава гурвалжин будаа 650 гр', 'Хараа 0.75 цэвэр',
       'Вигора 200 гр', 'Давс 1 кг', 'Mini cracker 350 гр',
       'Тоник лаазтай 330 мл', 'Tide 450 гр авто',
       'Paldo king noodle 110 гр', 'Цесна 25 кг', 'Appetita плова',
       'Саль ариун 100 ш', 'Слава каш 1 кг', 'Моя семъя 1 л',
       'Зуун наст 1.25 мл', 'Мандарин', 'Appetita будаатай хуурга',
       'Цэвэрхэн 00ийн цаас', 'Siesta үзэм 200 гр',
       'Махеевь салатны 400 мл', 'Selpak 2 хайрцаг', 'Oleina тос 1 л',
       'Чихэр кг Кокос 400 гр', 'Nivea тос 50 мл', 'Омо 100 гр',
       'Өгөөж вафли', 'Head & Shoulders 400 мл', 'Жимстэй чокопай 6 ш',
       'Соёолж 2.5 л', 'Тэргүүн 0.5', 'Витсамо ус 500 мл', 'Дашида 50 гр',
       'Заантай будаа 5 кг', 'Lays чипс 80 гр', 'Хавиргатай рагу 454 гр',
       'Хутга 1 ш', 'Нандин чавга 250 гр', 'Чинжүү',
       'Чихэр кг Конфет Кино 400 гр', 'Cocoro 100 гр', '3н өнгийн алчуур',
       'Оргилуун ус жимстэй 500 мл', 'Видан зөгийн бал',
       'Сор жүүс 200 мл', 'Гурвалжин шоко 22 гр', 'Гоё тетра 1 л',
       'Шпрот урт татдаг 190 гр', 'Bagro хүрэн манжингийн салат 500 мл',
       'Цагаан самар 50 гр', 'Махны мод дугуй', 'Биг ланч 110 гр савтай',
       'Custard 6 ш', 'Алтантүрүү 0.5', 'Фифти фифти 180 гр',
       'Hainich нухаш', 'Монстров 23 гр', 'Арвай 0.100',
       'Тэйсти гоймон 110 гр'], dtype=object)

In [33]:
#7 Product Name баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу
len(w)

94

In [34]:
#8 Product Name баганын давхардсан утгуудыг харуулна уу.

q[q.duplicated()]

31                 Помидор том
43      Arizona лаазтай 680 мл
72          Алое шилтэй 180 мл
75    Appetita будаатай хуурга
86            Хараа 0.75 цэвэр
96             Lays чипс 80 гр
Name: Product Name, dtype: object

In [35]:
#9 Order ID баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу
r=states['Order ID']
t=r.unique()
len(t)

50

In [43]:
#10 Бараа тус бүрээс хэдэн ширхэгийг зарсаныг харуулна уу

a = states.groupby(['Product Name']).sum()
a['Quantity']

Product Name
370 Жүүс 370 мл             5
3н өнгийн алчуур            3
A vodka 0.5                 3
Akuku резин 90 гр           3
Appetita будаатай хуурга    8
                           ..
Эгоист 65 гр                5
Үзгэн бал арилгадаг         6
Өглөө сүү                   3
Өгөөж вафли                 6
Өгөөж танзуур               3
Name: Quantity, Length: 94, dtype: int64

In [16]:
#11 Хамгийн өндөр дүнтэй борлуулалтыг (Order ID) олно уу. 

y = states.groupby(['Order ID']).sum()
y.sort_values('Sales', ascending=False)

                Price  Quantity  Discount     Sales
Order ID
CA-2016-169194  45450         5      0.00  135900.0
CA-2015-117415  19500        19      0.12   83808.0
CA-2014-115812  14200        38      0.00   83450.0
CA-2016-111682  22600        25      0.00   67700.0
CA-2014-106376   8100        12      0.00   62800.0
CA-2016-137330   8700        14      0.00   60900.0
CA-2015-135545  17150        15      0.00   58700.0
US-2015-150630  10640        28      0.00   51230.0
CA-2015-149587  17550         7      0.00   47600.0
CA-2016-105816   4850        12      0.00   33250.0
CA-2016-109806  15800         6      0.00   29800.0
CA-2015-115742   8500        15      0.00   28700.0
US-2015-164175   5700         5      0.03   27645.0
CA-2017-114412   9000         3      0.00   27000.0
US-2017-118038   6350         9      0.00   19050.0
US-2015-134026   7500        11      0.00   18600.0
CA-2017-155558  15000         3      0.00   18500.0
US-2015-108966   3950         7      0.00   16300.0
CA-2017-161018   2300         7      0.03   15617.0
US-2014-147606   3000         5      0.00   15000.0
CA-2016-159695   2200         7      0.03   14938.0
CA-2016-117590   2200        12      0.00   13600.0
CA-2016-106075  13200         1      0.00   13200.0
CA-2016-158568   1800         7      0.03   12222.0
CA-2016-149223   2000         6      0.00   12000.0
CA-2016-118255   5350         4      0.00   10700.0
CA-2014-105893   1600         6      0.00    9600.0
CA-2016-161389   3000         3      0.00    9000.0
CA-2014-146703   2200         4      0.00    8800.0
CA-2016-121755   3600         5      0.00    8700.0
CA-2014-139451   4350         6      0.00    8550.0
US-2015-118983   2150         8      0.06    8293.5
CA-2016-152156   3800         5      0.00    8100.0
CA-2017-107727   2600         3      0.03    7566.0
CA-2015-106320   2500         3      0.00    7500.0
CA-2014-143336   2650         9      0.00    7200.0
CA-2016-101343   3500         2      0.00    7000.0
CA-2017-114440   2300         3      0.00    6900.0
CA-2016-138688   3100         2      0.00    6200.0
CA-2016-127208   3400         4      0.00    5600.0
US-2017-156909   2500         2      0.00    5000.0
CA-2017-139619   2500         2      0.00    5000.0
CA-2015-149734    500         7      0.00    3500.0
US-2017-109484   3300         1      0.03    3201.0
CA-2017-140088   1600         2      0.00    3200.0
CA-2014-167164   1200         2      0.00    2400.0
US-2017-119662    600         3      0.03    1746.0
CA-2016-119823    800         2      0.00    1600.0
CA-2017-157833    500         3      0.00    1500.0
CA-2017-120999    200         4      0.00     800.0

In [11]:
#12 Хамгийн өндөр дүнтэй зарагдсан барааг (Sales) олно уу. 
import numpy as np
y_max= np.max(states['Sales'])
states.loc[states.Sales == y_max]

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
47,CA-2016-169194,20.06.16,CR-12580,Хувь хүн,Сүхбаатар,Гурил будаа,Цесна 25 кг,45000,3,0.0,135000.0